sudo: required
language: node_js
node_js:
    - "6"

cache:
  directories:
    - $HOME/.npm

services:
  - docker

script:
  - npm run build

after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
  docker push reactivesw/customer_web;