export const PRODUCT_PROJECTION = '/product-projections'
export const CATEGORIES = '/categories'
export const PRODUCTS = '/products'
export const PRODUCT_TYPES = '/product-types'
export const CARTS = '/carts'
