export const SIGN_UP = 'auth/SIGN_UP'
export const SIGN_IN = 'auth/SIGN_IN'
export const SET_CUSTOMER = 'auth/SET_CUSTOMER'
export const GET_CUSTOMER = 'auth/GET_CUSTOMER'
export const LOG_OUT = 'auth/LOG_OUT'
