export const SIGN_UP = 'auth/SIGN_UP'
export const SIGN_IN = 'auth/SIGN_IN'
export const SET_CUSTOMER = 'auth/SET_CUSTOMER'
export const GET_CUSTOMER = 'auth/GET_CUSTOMER'
export const SET_TOKEN = 'auth/SET_TOKEN'
export const GET_TOKEN = 'auth/GET_TOKEN'
export const SIGN_OUT = 'auth/SIGN_OUT'
